openapi: 3.0.1
info:
  title: Urbapp Api
  description: I am the Urbapp Utility API.
  termsOfService: 'https://swagger.io/tools/swaggerhub/'
  contact:
    email: juanramrom@gmail.com, angelillor@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: local enviroment
tags:
  - name: test
    description: test
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
  /login:
    get:
      operationId: login
      responses:
        '200':
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
components:
  schemas:

    TestResponse:
      type: object
      properties:
        value:
          description: test value
          type: string


